# .github/workflows/release.yml
name: goreleaser-pr

on:
  pull_request:
    paths-ignore:
      - "README.MD"
      - ".github/workflows/*"

permissions:
  contents: read

jobs:
  goreleaser:
    name: release build check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: build --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
